# Generated by Django 3.1.7 on 2021-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lend',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
