# Generated by Django 3.1.7 on 2021-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0002_cart_cart_line_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sales_type',
            field=models.CharField(choices=[('b', 'buy/sell'), ('l', 'lend'), ('e', 'exchange'), ('s', 'sold')], default='b', max_length=1),
        ),
    ]
