# Generated by Django 3.1.7 on 2021-04-14 08:49

from django.db import migrations, models
import ubs_project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0003_auto_20210412_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[ubs_project.validators.positive_number])),
                ('image', models.ImageField(upload_to='items')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('item_id', models.IntegerField(null=True)),
                ('rent_user_id', models.IntegerField()),
                ('lend_user_id', models.IntegerField()),
            ],
        ),
    ]
