# Generated by Django 3.2 on 2021-04-23 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0004_lend'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintreeId',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
