# Generated by Django 3.1.6 on 2021-02-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0005_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to='ubs_project.student'),
        ),
    ]
