# Generated by Django 3.1.6 on 2021-02-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0006_auto_20210214_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='student',
            field=models.ManyToManyField(related_name='joined_clubs', to='ubs_project.Student'),
        ),
    ]
