# Generated by Django 3.1.6 on 2021-02-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0007_auto_20210214_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales_type', models.CharField(choices=[('b', 'buy/sell'), ('l', 'lend'), ('e', 'exchange')], default='b', max_length=1)),
                ('status', models.CharField(choices=[('l', 'listing'), ('c', 'closed')], default='l', max_length=1)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs_project.student')),
            ],
        ),
    ]
