# Generated by Django 3.1.6 on 2021-02-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0008_merchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('card_type', models.CharField(choices=[('v', 'Visa'), ('m', 'Mastercard')], default='v', max_length=1)),
                ('cardholder_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=16)),
                ('security_code', models.CharField(max_length=3)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs_project.student')),
            ],
        ),
    ]
