# Generated by Django 3.1.7 on 2021-03-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ubs_project.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubs_project', '0012_auto_20210305_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[ubs_project.validators.positive_number])),
                ('image', models.ImageField(upload_to='items')),
                ('sales_type', models.CharField(choices=[('b', 'buy/sell'), ('l', 'lend'), ('e', 'exchange')], default='b', max_length=1)),
                ('status', models.CharField(choices=[('l', 'listing'), ('c', 'closed')], default='l', max_length=1)),
                ('created_at', models.DateTimeField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
