# Generated by Django 3.1.7 on 2021-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubs_project', '0012_auto_20210305_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
